name: Sonarcube Code Quality Check
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - dev
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    env:
      CLOCKIFY_API_KEY: ${{ secrets.CLOCKIFY_API_KEY }}
      TEST_WORKSPACE_ID: ${{ secrets.TEST_WORKSPACE_ID }}
      TEST_USER_ID: ${{ secrets.TEST_USER_ID }}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
      TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
      TEST_TASK_ID: ${{ secrets.TEST_TASK_ID }}
      TEST_TAG_ID: ${{ secrets.TEST_TAG_ID }}
      TEST_TIME_ENTRY_ID: ${{ secrets.TEST_TIME_ENTRY_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Run Jest
        run: npm run test

      - name: Upload Testing Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Testing Artifacts
        uses: actions/download-artifact@v2
        with:
          name: reports
          path: reports

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
